[project]
name = 'news'
channels = ['conda-forge']
platforms = ['linux-64', 'win-64']
authors = ['snekdesign']
license-file = 'LICENSE'
readme = 'README.md'
repository = 'https://github.com/snekdesign/news'

[dependencies]
conda = '*'
pydantic = '>=2.0.0'
py-rattler = '>=0.2.1'
pyyaml = '*'

[tasks]
check = 'python -m news.conda_update .news/conda_update.yml'
