cache_path: F:\var\conda
channels:
- conda-forge
platforms:
- linux-64
- noarch
- win-64
specs:
- boa >=0.16.1
- ffmpeg >=6.1.2
- libmamba >=2.0.0
- nginx >=1.25.4
- pixi >=0.14.0
- py-rattler >=0.3.0
- rattler-build >=0.8.2
- typing-extensions >=4.10.0
mirrored_channels:
- auto
- biobakery
- bioconda
- c4aarch64
- caffe2
- conda-forge
- deepmodeling
- dglteam
- fastai
- fermi
- idaholab
- intel
- matsci
- menpo
- MindSpore
- mordred-descriptor
- msys2
- numba
- ohmeta
- omnia
- Paddle
- peterjc123
- plotly
- psi4
- pytorch
- pytorch-lts
- pytorch-test
- pytorch3d
- pyviz
- qiime2
- rapidsai
- rdkit
- simpleitk
- stackless
- ursky
