cache_path: F:\var\conda\pkgs\cache
channels:
- conda-forge
platforms:
- linux-64
- noarch
specs:
- ffmpeg >=7.0.2
- libmamba >=2.0.0
- nginx >=1.26.1
- pixi >=0.24.0
- py-rattler >=0.6.3
- rattler-build >=0.16.3
- typing-extensions >=4.12.0
- vs2022_win-64 >=19.40.0
mirrored_channels:
- auto
- biobakery
- bioconda
- c4aarch64
- caffe2
- conda-forge
- deepmodeling
- dglteam
- fastai
- fermi
- idaholab
- intel
- matsci
- menpo
- MindSpore
- mordred-descriptor
- msys2
- numba
- ohmeta
- omnia
- Paddle
- peterjc123
- plotly
- psi4
- pytorch
- pytorch-lts
- pytorch-test
- pytorch3d
- pyviz
- qiime2
- rapidsai
- rdkit
- simpleitk
- stackless
- ursky
